CREATE DATABASE DTLOGIN
GO
USE DTLOGIN

CREATE TABLE USUARIO (
USUARIO VARCHAR (50) PRIMARY KEY,
NOME_COMPLETO VARCHAR (200),
EMAIL VARCHAR (100),
TELEFONE VARCHAR (9),
SENHA VARCHAR (20)
)

CREATE PROCEDURE BSC_USER (@USER VARCHAR(50), @PASS VARCHAR(20), @SAIDA VARCHAR(MAX) OUTPUT)
AS
IF EXISTS
(
	SELECT 1 FROM USUARIO
	WHERE CAST(USUARIO AS VARBINARY) = CAST(@USER AS VARBINARY)
	AND CAST(SENHA AS VARBINARY) = CAST(@PASS AS VARBINARY)
)
BEGIN
	SET @SAIDA = 'USUARIO ENCONTRADO'
END
ELSE
BEGIN
	SET @SAIDA = 'USUARIO OU SENHA INVALIDO'
END


CREATE PROCEDURE NOVO_USER (@USER VARCHAR(50), @NOME VARCHAR(200), @EMAIL VARCHAR (100), @TEL VARCHAR (9),
				 @PASS VARCHAR(20), @SAIDA VARCHAR(MAX) OUTPUT)
AS
BEGIN
	INSERT INTO USUARIO VALUES
	(@USER, @NOME, @EMAIL, @TEL, @PASS)

	SET @SAIDA = 'USUARIO CADASTRADO COM SUCESSO!'
END


declare @saida varchar (max)
exec novo_user 'teste12', 'fulano', 'abc@def.com', '971551123', 'novouser', @saida output
print @saida

declare @saida varchar (max)
exec bsc_user 'teste12', 'novouser', @saida output
print @saida